### ISSUE TITLE
load dietmatrix - not working for CEP/PWN

### ISSUE THREAD

**Issue by cecilieha** [alketh/atlantistools#10]
Hi Alex,

so sorry, I've tried to figure out in the code (load-dietmatrix.R) why the program does not load the diet of PWN and CEP correctly, but I'm not able to fix it. For some reason it expects diet in line with how the invertebrates are defined, but these two groups are (in my case at least) age-structured invertebrates, and hence have a pPREY1PWN1/pPREY2PWN1 etc structure. I get the following error message: Error in scan_prm(chars = prm, variable = variable) : 
  Variable pPREYPWN1 not found. Any ideas on how I can fix this?

**Comment by alketh** [comment]
@cecilieha please do not feel sorry. It's great to get feedback about the package. I am glad to help you out. In the current state of the package there are 3 categories of groups supported.
1. fully age structured groups identified by NumCohorts > 2
2. stanza based groups identified by NumCohorts == 2
3. non age structured groups with NumCohorts == 1
Do your age-structured invertebrates have more than 2 ageclasses?

**Comment by alketh** [comment]
@cecilieha I added some changes to the code and it now works for both the trunk and the example test files (not sure which code version you use). Have to run some more tests to make sure nothing else broke due to the changes. Will add the changes to the master branch afterwards. Will be back in roughly an hour.

**Comment by cecilieha** [comment]
Thank you so much Alex!! I’m running the trunk code, looking forward to test this:o) You’re making some really, really great (and extremely useful) tools!!

Cecilie




——————————————————————
Cecilie Hansen, PhD
Researcher
Ecosystem processes/Økosystemprosesser
Institute of Marine Research
Cecilie.hansen@imr.no
+47 984 31 016
——————————————————————



Fra: Alexander Keth <notifications@github.com>
Svar til: alketh/atlantistools <reply@reply.github.com>
Dato: fredag 4. november 2016 12.00
Til: alketh/atlantistools <atlantistools@noreply.github.com>
Kopi: Hansen Cecilie <cecilieha@IMR.no>, Mention <mention@noreply.github.com>
Emne: Re: [alketh/atlantistools] load dietmatrix - not working for CEP/PWN (#10)


@cecilieha<https://github.com/cecilieha> I added some changes to the code and it now works for both the trunk and the example test files (not sure which code version you use). Have to run some more tests to make sure nothing else broke due to the changes. Will add the changes to the master branch afterwards. Will be back in roughly an hour.

**Comment by alketh** [comment]
@cecilieha the code is updated now. Please make sure to install the newest version before you start testing with devtools::install_github("alketh/atlantistools"). Please keep in mind that the code will still break in case you use the following settings:
Stanza based groups (NumCohorts == 2) and pprey1XXX2, pprey2XXX2, pprey2XXX1, pprey2XXX2 settings in your biol.prm file. Based on the SETAS model files stanza based groups are implemented with ppreyXXX1 ppreyXXX2. However, it is possible (and a bit hacky) to update the code accordingly.
