### ISSUE TITLE
Possible issue with grep call in scan_prm ; manifests in prm_to_df 

### ISSUE THREAD

**Issue by RMORSEcode** [alketh/atlantistools#12]
Hi Alex,
I was running the preprocess and hit an issue while reading age at maturity:
# Read in misc
`df_agemat <- prm_to_df(dir = d2, prm_biol = prm_biol, fgs = fgs, group = get_age_acronyms(d2, fgs), parameter = "age_mat")
`
 Error in FUN(X[[i]], ...) : Variable SK_age_mat found multiple times. 

I tracked this down to a cascade of functions as detailed below -
1) prm_to_df : `values <- lapply(prms, extract_prm, dir = dir, prm_biol = prm_biol)`
```
prm_to_df = function (dir = getwd(), prm_biol, fgs, group, parameter) 
{
  prms <- lapply(parameter, set_single_prm, group = group)
  values <- lapply(prms, extract_prm, dir = dir, prm_biol = prm_biol)
  df <- as.data.frame(do.call(cbind, values))
  names(df) <- tolower(parameter)
  df$species <- group
  df$species <- convert_factor(data_fgs = load_fgs(dir = dir, 
                                                   fgs = fgs), col = df$species)
  df <- dplyr::select_(df, .dots = c("species", sort(names(df)[-ncol(df)])))
  return(df)
}
```
stepping through this function:
```
> prms <- lapply(group, function(x) set_single_prm(group , parameter="age_mat"))
> values <- lapply(prms, extract_prm, dir = dir, prm_biol = prm_biol)
Error in FUN(X[[i]], ...) : Variable SK_age_mat found multiple times.
```

2)exctract_prm : original code posted with new line as fix for my immediate problem, which may not be suitable for others
```
extract_prm <- function(dir = getwd(), prm_biol, variables) {
  # Read in parameter file!
  prm_biol_new <- convert_path(dir = dir, file = prm_biol)
  prm_biol_new <- readLines(con = prm_biol_new)

  pos <- vapply(variables, scan_prm, FUN.VALUE = integer(1), chars = prm_biol_new)
  #result <- prm_biol_new[pos] #original code
  result <- prm_biol_new[pos[1]:(length(pos)+pos[1]-1)] #modified RM
  result <- vapply(result, str_split_twice, FUN.VALUE = numeric(1), USE.NAMES = FALSE)
  return(result)
}
```
3) scan_prm seems to be where the problem begins :
`pos <- vapply(prms, scan_prm, FUN.VALUE = integer(1), chars = prm_biol_new)
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In grep(pattern = variable, x = chars) :
  argument 'pattern' has length > 1 and only the first element will be used`
-> It seems the error I was getting was a replication of just the very first maturity at age number (which would be whatever the first one is in the biol.prm file).

I think I solved my problem for the short term future by changing the index for the result call in extract_prm, but this may not be a universal fix.
Thanks so much,
Ryan

**Comment by alketh** [comment]
hmmm... that's very unfortunate :/

From my perspective, the best way to solve this is to make sure that every group-tag is not present in any other group tag in the first place. Of course, this is not helpful in any way at the current stage.

To be honest, the only solution I can think of is to somehow hard code the skate species. However, this might haunt us at later stages due to unwanted side-effects. Another solution might be to scan for any sort of whitespace (space, tab and so on) **before** the searched tag. Therefore one could crearly distinguish WSK_age_mat from SK_age_mat as they differ in white-space and "W".

**Comment by alketh** [comment]
@RMORSEcode I updated the `scan_prm()` function to make it work with nested flags. Thus, this also resulted in the removal of the hard coded "jmL", "mL", "mum", "crit_mum" exceptions which basically work in the same way. Currently, the first two characters are compared with each other to make sure nested flags are removed. Thus, when searching for "SK_age_mat", "WSK_age_mat" is removed as "SK" does not match"WS". I already merged the changes in the master branch. Please update the package and give it a go. Let me know how things worked out.

**Comment by RMORSEcode** [comment]
That worked perfectly, thanks so much Alex!
