### ISSUE TITLE
preprocess issues with files in multiple locations - and a quick fix

### ISSUE THREAD

**Issue by RMORSEcode** [alketh/atlantistools#14]
Hi Alex
My runs are set up so that files are saved in folder A, code is in folder B and parameter files are in folder C, so things are difficult using the built in 'dir' calls in much of the code. I have been calling the file location and setting 'dir'=NULL to avoid these issues, but then have run into snags with file checks like in load-bps.R

Because my file location contains multiple periods (e.g. "C:/Users/ryan.morse/Documents/GitHub/atneus_RM/RMinit_2.nc"), the following file check fails:

Original code:
load_bps <- function(dir = getwd(), fgs, init){
  if (strsplit(init, "\\.")[[1]][2] != "nc") {
    stop(paste("The init argument", init, "does not end in .nc"))
  }
  if (!is.null(dir)) {
    init <- file.path(dir, init)
  }

this is the line that fails -> (strsplit(init, "\\.")[[1]][2] != "nc")
but if you change it to this -> strsplit(init, "\\.")[[1]][length(strsplit(init, "\\.")[[1]])]
all works as it should as it finds the last period in the file sequence.

Replacement:
load_bps <- function(dir = getwd(), fgs, init){
  if (strsplit(init, "\\.")[[1]][length(strsplit(init, "\\.")[[1]])] != "nc") {
    stop(paste("The init argument", init, "does not end in .nc"))
  }
  if (!is.null(dir)) {
    init <- file.path(dir, init)
  }

Cheers,
Ryan

**Comment by alketh** [comment]
Hey Ryan!
I am so sorry. This issue must be really frustrating for end-users. To be honest the whole deal with "dir" dates way back when my coding skills were really poor. In my opinion the best fix would be to remove "dir" completely from the package and let the user handle the path creation himself. This has buged me for weeks and this really should get fixed. I am going to add your suggestion in the meantime.

**Comment by alketh** [comment]
The changes are now part of the master branch. Please make sure to update your local version of the package to include the most recent changes.

**Comment by mdsumner** [comment]
Awesome!  Best to make painful changes as early as possible :)
